### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "new@user.com",
    "password": "admin"
}

### Sign in as an existing user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "new@user.com",
    "password": "admin"
}

### Sign out
GET http://localhost:3000/auth/signout


### Check current user
GET http://localhost:3000/auth/whoami

### Find a particular user with an id
GET http://localhost:3000/auth/1


### Find all users with a given email
GET http://localhost:3000/auth?email=test@test.com

### Delete a user given id
DELETE http://localhost:3000/auth/5

### Update a user
PATCH http://localhost:3000/auth/5
Content-Type: application/json

{
    "password": "admin"
}

### Create a vehicle report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Ford",
    "model": "Mustang",
    "year": 1984,
    "mileage": 120000,
    "lng": 45,
    "lat": 45,
    "price": 30000

}

### Approve a vehicle report
PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
    "approved": true
}

### Get an estimate for an existing vehicle
GET http://localhost:3000/reports?make=Ford&model=Mustang&lat=45&lng=45&mileage=130000&year=1984